name: presto-complete.test
label: 消色散
cluster: p419
parameters:
  initial_status: RUNNING
  message_router: message-router-presto

jobs:
  # dir-list-1:
  #   base_image: hub.cstcloud.cn/scalebox/dir-list
  #   parameters:
  #     slot_on_head: yes
  #   hosts:
  #     - h0:1

  dir-list:
    base_image: hub.cstcloud.cn/scalebox/dir-listx
    parameters:
      slot_on_head: yes
      # scalebox@159.226.237.136/raid0/scalebox/mydata/mwa/24ch-240408~1257010784
      # key_group_regex: ^([^~])~([0-9]+)/p([0-9]+)
      # key_group_index: 2,3
    hosts:
      - h0:1

  local-copy:
    base_image: ${FILE_COPY}
    command: ${PRIVILEGED_COMMAND}
    variables:
      task_timeout_seconds: 1800
      # code_path: ${CODE_BASE}/dockerfiles/presto-modules/local-copy-unpack/code
      # dir_limit_gb: ${UNPACK_LIMIT_GB} #/tmp/data/mwa/24ch
      # dir_free_gb: ${UNPACK_FREE_GB}
      dir_limit_gb: ${SHARED_ROOT}/24ch~12800
      max_sleep_count: ${NODE_MAX_SLEEP_COUNT}
    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      # 1257010784/p00001/t1257010786_1257010935.fits.zst
      key_group_regex: ^([^/]+)/p([0-9]+)/(.+)$
      key_group_index: 1,2
      message_router_index: 1
      pod_id: 1
      bulk_message_size: 2
      retry_rules: "['2:2']"
      repeatable: yes
    environments:
      # - JUMP_SERVERS=${JUMP_SERVERS}
      - SOURCE_URL=${SOURCE_DIR}
      - TARGET_URL=${SHARED_ROOT}/mwa/24ch
    hosts:
      - n0:2

  # local-copy-unpack:
  #   base_image: ${FILE_COPY}
  #   command: ${PRIVILEGED_COMMAND}
  #   variables:
  #     task_timeout_seconds: 1800
  #     code_path: ${CODE_BASE}/dockerfiles/presto-modules/local-copy-unpack/code
  #     dir_limit_gb: ${UNPACK_LIMIT_GB} #/tmp/data/mwa/24ch
  #     dir_free_gb: ${UNPACK_FREE_GB}
  #     max_sleep_count: ${NODE_MAX_SLEEP_COUNT}
  #   parameters:
  #     task_dist_mode: ${TASK_DIST_MODE}
  #     # scalebox@159.226.237.136/raid0/scalebox/mydata/mwa/24ch-240408~1257010784/p00001/t1257010786_1257010935.fits.zst
  #     key_group_regex: ^([^~]+)~([^/]+)/p([0-9]+)/(.+)$
  #     key_group_index: 2,3
  #     message_router_index: 1
  #     pod_id: 1
  #     bulk_message_size: 2
  #     retry_rules: "['2:2']"
  #     repeatable: yes
  #   environments:
  #     - JUMP_SERVERS=${JUMP_SERVERS}
  #   hosts:
  #     - ${NODES}:1

  rfi-find:
    label: rfi-find-test
    base_image: ${PRESTO_SEARCH}
    command: ${PRIVILEGED_COMMAND}
    variables:
      max_sleep_count: ${NODE_MAX_SLEEP_COUNT}
      task_timeout_seconds: 43200
      output_text_size: 1048576
      code_path: ${CODE_BASE}/dockerfiles/presto-modules/rfi-find/code
      dir_limit_gb: ${UNPACK_LIMIT_GB} #/tmp/data/mwa/24ch
      dir_free_gb: ${UNPACK_FREE_GB}
      
    environments:
      - KEEP_SOURCE_FILE=no
      - LOCAL_INPUT_ROOT=${LOCAL_FITS_ROOT}
      - LOCAL_OUTPUT_ROOT=${LOCAL_SHM_ROOT}
      - SHARED_ROOT=${SHARED_ROOT}
      - MAX_LINENUM=${MAX_LINENUM}
      - RFIARGS=${RFIARGS}
    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      # task_dist_mode: HOST-BOUND
      # 1257010784/p00001
      key_group_regex: ^([^/]+)/p([0-9]+)$
      key_group_index: 1,2
      # start_message: ${START_MESSAGE}
      pod_id: 1
      retry_rules: "['2:2']"
      repeatable: yes
    hosts:
      - ${NODES}:1
    # sink_jobs:
    #   - dedisp-search
  
  dedisp-search:
    label: dedisp-search-test
    base_image: ${PRESTO_SEARCH}
    command: ${ROCM_COMMAND}
    variables:
      max_sleep_count: ${NODE_MAX_SLEEP_COUNT}
      task_timeout_seconds: 43200
      output_text_size: 1048576
      code_path: ${CODE_BASE}/dockerfiles/presto-modules/dedisp-search/code
      # 最大占用4.8G*4组，外加4.8G*4临时空间，外加4.8G*4已完成处理数据，共57.6G;至少9.6G保证单个slot正确运行
      dir_limit_gb: ${DEDISP_DIR_LIMIT_GB}
      dir_free_gb: ${DEDISP_DIR_FREE_GB}
      
    environments:
      - KEEP_SOURCE_FILE=yes
      - LOCAL_INPUT_ROOT=${LOCAL_FITS_ROOT}
      - LOCAL_OUTPUT_ROOT=${LOCAL_SHM_ROOT}
      - NSUB=${NSUB}
      - NCPUS=${NCPUS}
      - SEARCHARGS=${SEARCHARGS}
      # - ROCR_VISIBLE_DEVICES=${DEVICE_TO_USE}

    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      # 1257010784/p00001/01
      key_group_regex: ^([^/]+)/p([0-9]+)/([0-9]+)$
      key_group_index: 1,2,3
      message_router_index: 1
      retry_rules: "['2:2','13:3','14:3']"
      repeatable: yes
      pod_id: 1
    hosts:
      - ${NODES}:4

  fold:
    label: presto-search-fold-test
    base_image: ${PRESTO_SEARCH}
    # command: ${ROCM_COMMAND}
    
    variables:
      max_sleep_count: ${NODE_MAX_SLEEP_COUNT}
      task_timeout_seconds: 43200
      output_text_size: 1048576
      code_path: ${CODE_BASE}/dockerfiles/presto-modules/fold/code
      dir_limit_gb: ${FOLD_LIMIT_GB}
      dir_free_gb: ${FOLD_FREE_GB}
      
    environments:
      - KEEP_SOURCE_FILE=no
      - LOCAL_INPUT_ROOT=${LOCAL_SHM_ROOT}
      - LOCAL_OUTPUT_ROOT=${LOCAL_SHM_ROOT}
      - SHARED_ROOT=${SHARED_ROOT}
      # - LOCAL_OUTPUT_ROOT=/raid0/zhzhang/data
      # - ROCR_VISIBLE_DEVICES=0
      - SEARCHARGS=${SEARCHARGS}
    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      # 1257010784/1257010786_1257010795/00001
      # key_group_regex: ^(.+)$
      pod_id: 1
      retry_rules: "['2:2']"
      repeatable: yes
    hosts:
      - ${NODES}:1

  # clean-up:
  #   base_image: ${PRESTO_SEARCH}
  #   parameters:
  #     task_dist_mode: ${TASK_DIST_MODE}
  #   environments:
  #     - LOCAL_FITS_ROOT=${LOCAL_FITS_ROOT}
  #     - LOCAL_DEDISP_ROOT=${LOCAL_SHM_ROOT}
  #   variables:
  #     code_path: ${CODE_BASE}/dockerfiles/presto-modules/clean-up/code
  #     max_sleep_count: 4800
  #   hosts:
  #     - ${NODES}:1

  result-push:
    base_image: ${FILE_COPY}
    variables:
      task_timeout_seconds: 1800
      max_sleep_count: ${NODE_MAX_SLEEP_COUNT}
    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      # /dev/shm/scalebox/mydata/mwa/png~1257010784/p00016/dm1.tar.zst~scalebox@159.226.237.136/raid0/scalebox/mydata/mwa/png
      key_group_regex: ^.+~([0-9]+)/p([0-9]{5})/t([0-9]+_[0-9]+)~.+$
      key_group_index: 1,3,2
      retry_rules: "['255:2']"
    environments:
      - KEEP_SOURCE_FILE=no
      - JUMP_SERVERS=${JUMP_SERVERS}
      - SOURCE_URL=${SHARED_ROOT}/mwa/png
      - TARGET_URL=${RESULT_DIR}
      - TARGET_JUMP_SERVERS=${JUMP_SERVERS}
      - WITH_HEADERS=yes
    hosts:
      -  ${NODES}:1

  message-router-presto:
    label: 主消息路由
    base_image: app-mwa/agent-with-ssh
    parameters:
      # slot_on_head: yes
      start_message: ${TARGET_POINTING}
      bulk_message_size: 40
      task_dist_mode: SLOT-BOUND
    variables:
      code_path: ${CODE_BASE_HEAD}/pipelines/presto-search/message-router/code
    environments:
      - LOG_LEVEL=warn
      - WITH_HEADERS=yes
      - LOCAL_MODE=
      - TRACE=
      - LOCAL_FITS_ROOT=${LOCAL_FITS_ROOT}
      - LOCAL_SHM_ROOT=${LOCAL_SHM_ROOT}
      - DATASET_URI=${TARGET_POINTING}
      - MAX_LINENUM=${MAX_LINENUM}
      - RESULT_DIR=${RESULT_DIR}
      - SOURCE_DIR=${SOURCE_DIR}
      - LOCAL_IP_INDEX=${MESSAGE_ROUTER_LOCAL_IP_INDEX}
      - DEFAULT_USER=${DEFAULT_USER}
      - SSH_PORT=${SSH_PORT}
      - NUM_OF_NODES=${NUM_OF_NODES}
      - POINTING_BEGIN=${POINTING_BEGIN}
      - POINTING_END=${POINTING_END}
      - NODES_GROUP=${NODES_GROUP}
    hosts:
      - h0:2
    sink_jobs:
      # - dir-list-1
      - dir-list
      # - rsync-pull
      # - local-copy-unpack
      - local-copy
      - rfi-find
      # - dedisp
      # - search
      - dedisp-search
      - fold
      - clean-up
      - result-push