name: main.app-mwa
label: comput
cluster: dcu
parameters:
  initial_status: RUNNING
  default_message_router: message-router-main

jobs:
  copy-untar:
    base_image: hub.cstcloud.cn/scalebox/agent

  dir-list:
    base_image: hub.cstcloud.cn/scalebox/cluster-dir-list
    schedule_mode: HEAD
    variables:
      # 10 minutes
      max_sleep_count: 100
    environments:
      - REGEX_FILTER=${REGEX_FILTER}
      - REGEX_2D_DATASET=${REGEX_DAT}
      - INDEX_2D_DATASET=${INDEX_DAT}

  data-grouping-main:
    label: dat分组
    base_image: hub.cstcloud.cn/scalebox/data-grouping-2d
    schedule_mode: HEAD
    command: docker run -d -P {{ENVS}} {{VOLUMES}} {{IMAGE}}
    parameters:
      key_group_regex: ${DAT_REGEX}
      key_group_index: ${DAT_INDEX}
      visiable: no
      # exit_code=1, entity message precedes metadata message, retry
      retry_rules: "['1']"
    environments:
      - COORD_TYPE=integer
      - DATASET_PREFIX=mwa

  beam-maker:
    label: beam-maker
    base_image: app-mwa/beam-maker
    command: docker run -d --rm
        --group-add video 
        --device /dev/kfd 
        --device /dev/dri/card1
        --device /dev/dri/renderD129 
        --security-opt seccomp=unconfined 
        --network=host {{ENVS}} {{VOLUMES}} {{IMAGE}}
    variables:
      max_sleep_count: 100
      task_timeout_seconds: 300
    parameters:
      # 1257010784/1257010806_1257010815/131/00001_00003
      key_group_regex: ^([0-9]+)/([0-9]+_[0-9]+)/([0-9]+)/[0-9]{5}_[0-9]{5}$
      key_group_index: 1,3,2
    hosts:
      - n[01]:2

  down-sampler:
    base_image: app-mwa/down-sampler

  fits-dist:
    base_image: hub.cstcloud.cn/scalebox/rsync-copy

  fits-merger:
    label: 24通道fits合并
    base_image: app-mwa/fits-merger
    variables:
    # 10-min
      max_sleep_count: 100
      task_timeout_seconds: 60
    parameters:
      # 1257010784/1257010786_1257010795/00001
      key_group_regex: ^([0-9]+)/([0-9]+_[0-9]+)/[0-9]{5}$
      key_group_index: 1,3,2
    hosts:
      - n0:1

  message-router-main:
    label: 主消息路由
    base_image: app-mwa/message-router-go
    schedule_mode: HEAD
    variables:
      max_sleep_count: 50
    parameters:
      key_group_regex: ${MR_REGEX}
      key_group_index: ${MR_INDEX}
      start_message: ${DIR_NAME}
      visiable: no
    environments:
      - NUM_PER_GROUP=${NUM_PER_GROUP}
      - LOG_LEVEL=warn
    sink_jobs:
      - dir-list
      - data-grouping-main
      - beam-maker
      - down-sampler
      - fits-dist
      - fits-merger
