name: main.app-mwa
label: mwa-comput
cluster: ${CLUSTER}
parameters:
  initial_status: RUNNING
  default_message_router: message-router-main

jobs:
  dir-list:
    base_image: hub.cstcloud.cn/scalebox/dir-list
    cluster: ${CLUSTER_LOCAL}
    schedule_mode: HEAD
    variables:
      # 10 minutes
      max_sleep_count: 100
    environments:
      - REGEX_FILTER=${REGEX_FILTER}
      # - REGEX_2D_DATASET=${REGEX_DAT}
      # - INDEX_2D_DATASET=${INDEX_DAT}

  cluster-copy-tar:
    base_image: hub.cstcloud.cn/scalebox/cluster-file-copy
    cluster: ${CLUSTER_LOCAL}
    variables:
      max_sleep_count: 100
      task_timeout_seconds: 1800

  local-copy-tar:
    base_image: hub.cstcloud.cn/scalebox/cluster-file-copy
    variables:
      max_sleep_count: 100
      task_timeout_seconds: 180
    queue_mode: ${QUEUE_MODE}

  copy-unpack:
    base_image: ${COPY_UNPACK}
    queue_mode: ${QUEUE_MODE}
    variables:
      max_sleep_count: 100
      task_timeout_seconds: 1800
    environments:
      # - LOCAL_INPUT_ROOT=${LOCAL_DISK_ROOT}
      - LOCAL_OUTPUT_ROOT=${LOCAL_DISK_ROOT}
      - KEEP_SOURCE_FILE=yes
      - DIR_LIMIT_GB=/tmp/scalebox/mydata/mwa~20
    hosts:
      - n[01]:1

  beam-maker:
    label: beam-maker
    base_image: ${BEAM_MAKER}
    queue_mode: ${QUEUE_MODE}
    command: ${ROCM_COMMAND}
    # command: docker run -d --rm
    #     --group-add video 
    #     --device /dev/kfd 
    #     --device /dev/dri/card1
    #     --device /dev/dri/renderD129 
    #     --security-opt seccomp=unconfined 
    #     --network=host {{ENVS}} {{VOLUMES}} {{IMAGE}}
    variables:
      max_sleep_count: 100
      task_timeout_seconds: ${BEAM_MAKER_TIMEOUT}
    parameters:
      # 1257010784/1257010806_1257010815/131/00001_00003
      key_group_regex: ^([0-9]+)/([0-9]+_[0-9]+)/([0-9]{3})/[0-9]{5}_[0-9]{5}$
      key_group_index: 1,3,2
    environments:
      - LOCAL_INPUT_ROOT=${LOCAL_DISK_ROOT}
      - LOCAL_OUTPUT_ROOT=${LOCAL_SHM_ROOT}
      - KEEP_SOURCE_FILE=${KEEP_SOURCE_FILE}
    hosts:
      - n[01]:1

  down-sampler:
    base_image: ${DOWN_SAMPLER}
    queue_mode: ${QUEUE_MODE}
    environments:
      - KEEP_SOURCE_FILE=${KEEP_SOURCE_FILE}
      - LOCAL_INPUT_ROOT=${LOCAL_SHM_ROOT}
      - LOCAL_OUTPUT_ROOT=${LOCAL_SHM_ROOT}

  # push 
  fits-dist:
    base_image: ${FITS_DIST}
    queue_mode: ${QUEUE_MODE}
    variables:
    # 10-min
      max_sleep_count: 100
      task_timeout_seconds: 60
    environments:
      - KEEP_SOURCE_FILE=${KEEP_SOURCE_FILE}
    hosts:
      - n[01]:1

  fits-merger:
    label: 24通道fits合并
    base_image: ${FITS_MERGER}
    queue_mode: ${QUEUE_MODE}
    variables:
    # 10-min
      max_sleep_count: 100
      task_timeout_seconds: ${FITS_MERGER_TIMEOUT}
    parameters:
      # 1257010784/1257010786_1257010795/00001
      key_group_regex: ^([0-9]+)/([0-9]+_[0-9]+)/[0-9]{5}$
      key_group_index: 1,2,3
    environments:
      - KEEP_SOURCE_FILE=${KEEP_SOURCE_FILE}
      - LOCAL_INPUT_ROOT=${LOCAL_SHM_ROOT}
      - LOCAL_OUTPUT_ROOT=${LOCAL_SHM_ROOT}
    hosts:
      - n[01]:1

  message-router-main:
    label: 主消息路由
    base_image: app-mwa/message-router-go
    cluster: ${CLUSTER_LOCAL}
    schedule_mode: HEAD
    variables:
      max_sleep_count: 50
    parameters:
      key_group_regex: ${MR_REGEX}
      key_group_index: ${MR_INDEX}
      start_message: ${START_MESSAGE}
      visiable: no
    environments:
      - NUM_PER_GROUP=${NUM_PER_GROUP}
      - LOG_LEVEL=warn
      - LOCAL_MODE=${LOCAL_MODE}
      - NUM_NODES_PER_GROUP=2
      - NUM_POINTINGS_PER_CALC=2
      # - TRACE=yes
    sink_jobs:
      - dir-list
      - cluster-copy-tar
      - copy-unpack
      - beam-maker
      - down-sampler
      - fits-dist
      - fits-merger
      - data-grouping-main

  data-grouping-main:
    label: dat/fits分组
    base_image: hub.cstcloud.cn/scalebox/data-grouping-2d
    cluster: ${CLUSTER_LOCAL}
    schedule_mode: HEAD
    command: docker run -d -P {{ENVS}} {{VOLUMES}} {{IMAGE}}
    parameters:
      key_group_regex: ${DAT_REGEX}
      key_group_index: ${DAT_INDEX}
      visiable: no
      # exit_code=1, entity message precedes metadata message, retry
      retry_rules: "['1']"
    environments:
      - COORD_TYPE=integer
      - DATASET_PREFIX=mwa
    sink_jobs:
      - beam-maker
      - fits-merger
