name: main.app-mwa
label: mwa-comput
cluster: ${CLUSTER}
parameters:
  initial_status: RUNNING
  message_router: message-router-main
  default_sleep_count: 20

jobs:
  dir-list:
    base_image: hub.cstcloud.cn/scalebox/dir-list
    parameters:
      slot_on_head: yes
    environments:
      - REGEX_FILTER=${REGEX_FILTER}

  cluster-tar-pull:
    base_image: hub.cstcloud.cn/scalebox/rsync-copy
    variables:
      task_timeout_seconds: 1800
    parameters:
      # user@host/remote-path~1257010784/1257010786_1257010815_ch109.dat.tar.zst~/data/mwa/tar
      key_group_regex: ${REGEX_TAR}
      key_group_index: 1,2,3
    hosts:
      - h0:2

  pull-unpack:
    base_image: ${FILE_COPY}
    # node1上的文件读取错误，需设置特权权限。可能更新该节点上docker到最新版本可解决该问题
    command: ${PRIVILEGED_COMMAND}
    variables:
      code_path: ${CODE_BASE}/dockerfiles/pull-unpack/code
      task_timeout_seconds: 1800
      # 2 tar.zst files allowed in tmpfs
      # 下采样基本完成后，再重新传远端的打包文件（tar.zst）
      # SSD最多存放2组数据，beam-maker单次处理150秒，则最多存放300秒数据（300秒 * 313MB/秒 = 92GB ）
      dir_limit_gb: /tmp/scalebox/mydata/mwa/dat~95
      dir_free_gb: /tmp/scalebox/mydata/mwa/dat~15
      progress_counter_diff: 3
    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      # /raid0/scalebox/mydata/mwa/tar~1257010784/1257010786_1257010815_ch114.dat.tar.zst~/dev/shm/scalebox/mydata/mwa/tar
      key_group_regex: ^([0-9]+)/([0-9]+_[0-9]+)_ch([0-9]+).+$
      key_group_index: 1,2,3
      # message_router_index: 1
    environments:
      - LOCAL_OUTPUT_ROOT=${LOCAL_DISK_ROOT}
      - JUMP_SERVERS=${JUMP_SERVERS}
      - WITH_HEADERS=yes
      # 可给message-router发送重复名的消息（覆盖）
      - SOFT_OUTPUT_MB=
      - HARD_OUTPUT_MB=
    hosts:
      -  ${NODES}:1

  beam-maker:
    label: beam-maker
    base_image: ${MWA_VCSTOOLS}
    command: ${ROCM_COMMAND}
    variables:
      task_timeout_seconds: ${BEAM_MAKER_TIMEOUT}
      dir_free_gb: /dev/shm/scalebox/mydata~{~n*5+15~}
      code_path: ${CODE_BASE}/dockerfiles/mwa-vcstools/beam-maker/code
      # output_text_size: 1048576
      progress_counter_diff: 96
      slot_options: reserved_on_exit
    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      slot_timeout_seconds: 60
      # 1257010784/1257010786_1257010845/109/00001_00024
      key_group_regex: ^([0-9]+)/([0-9]+_[0-9]+)/([0-9]{3})/([0-9]{5}_[0-9]{5})$
      # 若节点少，每个节点处理多于一个channel，则为 1,3,2
      # 若节点多，每个节点处理1个channel，则顺序为：1,2,4
      key_group_index: 1,3,2
      # message_router_index: 1
    environments:
      - LOCAL_INPUT_ROOT=${LOCAL_DISK_ROOT}
      # - LOCAL_CAL_ROOT=${LOCAL_SHM_ROOT}
      - LOCAL_OUTPUT_ROOT=${LOCAL_SHM_ROOT}
      - ZSTD_TARGET_FILE=yes
      - SOFT_OUTPUT_MB=
      - HARD_OUTPUT_MB=
      # 通常无KEEP_SOURCE_FILE设置，由信号量统一管理何时删除原始文件，仅压力测试时需使用
    hosts:
      - ${NODES}:4

  down-sampler:
    base_image: ${DOWN_SAMPLER}
    command: ${PRIVILEGED_COMMAND}
    variables:
      task_timeout_seconds: ${DOWN_SAMPLER_TIMEOUT}
      dir_free_gb: /dev/shm/scalebox/mydata~8
      code_path: ${CODE_BASE}/dockerfiles/down-sampler/code
    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      slot_timeout_seconds: 60
      # 1257010784/p00166/t1257010786_1257010845/ch117.fits
      key_group_regex: ^([0-9]+)/p([0-9]+)/t([0-9]+_[0-9]+)/ch([0-9]{3}).fits$
      key_group_index: 1,2,3
    environments:
      - KEEP_SOURCE_FILE=no
      - LOCAL_INPUT_ROOT=${LOCAL_SHM_ROOT}
      - LOCAL_OUTPUT_ROOT=${LOCAL_SHM_ROOT}
      - SOFT_OUTPUT_MB=
      - HARD_OUTPUT_MB=
    hosts:
      - ${NODES}:1

  # push 
  fits-redist:
    base_image: ${FILE_COPY}
    variables:
      task_timeout_seconds: 60
      dir_free_gb: /dev/shm/scalebox/mydata~10
    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      slot_timeout_seconds: 60
      # /scalebox/mydata/mwa/1chx~1257010784/p00088/t1257010786_1257010845/ch119.fits.zst~root@10.11.16.79/dev/shm/scalebox/mydata/mwa/1chx
      key_group_regex: ^.+~([0-9]+)/p([0-9]+)/t([0-9]+_[0-9]+)/ch([0-9]{3}).fits.zst~.+$
      key_group_index: 1,2,3
    environments:
      - TARGET_URL=/dev/shm/scalebox/mydata/mwa/1chx
      - WITH_HEADERS=yes
      - KEEP_SOURCE_FILE=no
      - SOFT_OUTPUT_MB=
      - HARD_OUTPUT_MB=
    hosts:
      - ${NODES}:1

  fits-merger:
    label: 24通道fits合并
    base_image: ${MWA_VCSTOOLS}
    variables:
      task_timeout_seconds: ${FITS_MERGER_TIMEOUT}
      dir_free_gb: /dev/shm/scalebox/mydata~8
      code_path: ${CODE_BASE}/dockerfiles/mwa-vcstools/fits-merger/code
    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      # 1257010784/1257010786_1257010795/00001
      # 1257010784/p00097/t1257010786_1257010845
      key_group_regex: ^([0-9]+)/p([0-9]{5})/t([0-9]+_[0-9]+)$
      key_group_index: 1,2,3
    environments:
      - KEEP_SOURCE_FILE=${KEEP_SOURCE_FILE}
      - LOCAL_INPUT_ROOT=${LOCAL_SHM_ROOT}
      - LOCAL_OUTPUT_ROOT=${LOCAL_SHM_ROOT}
      - SOFT_OUTPUT_MB=
      - HARD_OUTPUT_MB=
    hosts:
      - ${NODES}:1

  fits-24ch-push:
    base_image: ${FILE_COPY}
    variables:
      task_timeout_seconds: 1800
    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      # /dev/shm/scalebox/mydata/mwa/24ch~1257010784/p00016/t1257010786_1257010845.fits.zst~scalebox@159.226.237.136/raid0/scalebox/mydata/mwa/24ch
      key_group_regex: ^.+~([0-9]+)/p([0-9]{5})/t([0-9]+_[0-9]+)~.+$
      key_group_index: 1,3,2
    environments:
      - KEEP_SOURCE_FILE=no
      - SOURCE_URL=/dev/shm/scalebox/mydata/mwa/24ch
      - TARGET_URL=scalebox@159.226.237.136:10022/raid0/scalebox/mydata/mwa/24ch
      - TARGET_JUMP_SERVERS=${JUMP_SERVERS}
      - WITH_HEADERS=yes
    hosts:
      -  ${NODES}:1

  message-router-main:
    label: 主消息路由
    base_image: app-mwa/message-router-go
    parameters:
      # slot_on_head: yes
      key_group_regex:
      key_group_index:
      start_message: ${DATASET_URI}
      visiable: no
      task_dist_mode: SLOT-BOUND
    environments:
      - LOG_LEVEL=warn
      - LOCAL_MODE=${LOCAL_MODE}
      - BATCH_INSERT=yes
      # 设置JUMP_SERVERS，则远端tar也通过local-tar-pull直接获取
      - JUMP_SERVERS=${JUMP_SERVERS}
      - DATASET_URI=${DATASET_URI}
      - NUM_OF_NODES=${NUM_OF_NODES}
      - LOCAL_IP_INDEX=${MESSAGE_ROUTER_LOCAL_IP_INDEX}
      # - TRACE=yes
    hosts:
      - h0:2
    sink_jobs:
      - dir-list
      - cluster-tar-pull
      - pull-unpack
      - beam-maker
      - down-sampler
      - fits-redist
      - fits-merger
      - fits-24ch-push
