name: app-base.beam-form
cluster: ${CLUSTER}
parameters:
  initial_status: RUNNING
  message_router: mr-beam-form

modules:
  beam-make:
    base_image: ${MWA_VCSTOOLS}
    command: ${ROCM_COMMAND}
    arguments:
      code_path: ${CODE_BASE}/beam-make/code
      task_max_seconds: 3600
      # slot容错
      task_min_seconds: 30
      slot_options: tmpfs_workdir
    parameters:
      task_dist_mode: ${TASK_DIST_MODE}
      pod_id: ${POD_ID}
      key_group_regex: ^([0-9]+)
      retry_rules: "['*:2','134:9','139:9']"
      # max_tasks_per_minute: 3
      task_cache_expired_minutes: 65
    environments:
      - INPUT_ROOT=
      - OUTPUT_ROOT=${FITS_ROOT}
      - KEEP_TARGET_FILE=yes
      - POINTING_FILE=
      # - POINTING_FILE=pointing-250313.txt
      - POINTING_RANGE=
      - ZSTD_TARGET_FILE=no
      # 设置临时目录下的文件所属组
      - TMPDIR_GROUP=39
    slots:
      - ${NODES}:4
    sink_modules:
      - down-sample

  down-sample:
    base_image: ${DOWN_SAMPLE}
    command: ${DOWN_SAMPLE_COMMAND}
    arguments:
      # 20-min
      max_sleep_count: 200
      code_path: ${CODE_BASE}/down-sample/code
      slot_options: tmpfs_workdir
    parameters:
      key_group_regex: ^([0-9]+)
      retry_rules: "['*:2']"
      task_dist_mode: ${TASK_DIST_MODE}
      pod_id: ${POD_ID}
    environments:
      - INPUT_ROOT=${FITS_ROOT}
      - OUTPUT_ROOT=
      - KEEP_SOURCE_FILE=no
      - KEEP_TARGET_FILE=
      - ENABLE_LOCAL_COMPUTE=${ENABLE_LOCAL_COMPUTE}
      - ZSTD_TARGET_FILE=no
      - TMPDIR_GROUP=39
    slots:
      - ${NODES}

  fits-merge:
    label: 24通道fits合并
    base_image: ${MWA_VCSTOOLS}
    arguments:
    # 1 hour
      max_sleep_count: 720
      code_path: ${CODE_BASE}/fits-merge/code
      slot_options: tmpfs_workdir
    parameters:
      key_group_regex: ^([0-9]+)
      retry_rules: "['*:2']"
    environments:
      - INPUT_ROOT=
      - OUTPUT_ROOT=${OUTPUT_ROOT_24CH}
      - KEEP_SOURCE_FILE=no
      - ZSTD_TARGET_FILE=no
      - TMPDIR_GROUP=39
    slots:
      - ${NODES}

  mr-beam-form:
    base_image: app-mwa/message-router-beam-form-app-base
    parameters:
      key_group_regex: ^([0-9]+)$
      start_message: ${START_MESSAGE}
    environments:
      - TIME_STEP=${TIME_STEP}
      - WITH_POINTING_PATH=no
    slots:
      - h0:1
