name: app-base.beam-form
cluster: ${CLUSTER}
parameters:
  initial_status: RUNNING
  message_router: message-router-beam-form

jobs:
  beam-make:
    base_image: ${MWA_VCSTOOLS}
    command: ${ROCM_COMMAND}
    arguments:
      code_path: ${CODE_BASE}/beam-make/code
      task_timeout_seconds: 3600
    parameters:
      key_group_regex: ^([0-9]+)
      retry_rules: "['*']"
      max_tasks_per_minute: 3
      task_cache_expired_minutes: 65
    environments:
      - INPUT_ROOT=
      - OUTPUT_ROOT=
      - KEEP_TARGET_FILE=yes
      - POINTING_RANGE=${POINTING_RANGE}
    hosts:
      - ${NODES}:4
    sink_jobs:
      - down-sample

  down-sample:
    base_image: ${DOWN_SAMPLE}
    command: ${DOWN_SAMPLE_COMMAND}
    arguments:
      # 20-min
      max_sleep_count: 200
      code_path: ${CODE_BASE}/down-sample/code
    parameters:
      key_group_regex: ^([0-9]+)
    environments:
      - INPUT_ROOT=
      - OUTPUT_ROOT=
      - KEEP_SOURCE_FILE=no
      - KEEP_TARGET_FILE=
      - ENABLE_LOCAL_COMPUTE=${ENABLE_LOCAL_COMPUTE}
    hosts:
      - ${NODES}

  fits-merge:
    label: 24通道fits合并
    base_image: ${MWA_VCSTOOLS}
    arguments:
    # 1 hour
      max_sleep_count: 720
      code_path: ${CODE_BASE}/fits-merge/code
    parameters:
      key_group_regex: ^([0-9]+)
    environments:
      - INPUT_ROOT=
      - OUTPUT_ROOT=
      - KEEP_SOURCE_FILE=no
    hosts:
      - ${NODES}

  message-router-beam-form:
    base_image: app-mwa/message-router-beam-form-app-base
    parameters:
      key_group_regex: ^([0-9]+)$
      start_message: ${START_MESSAGE}
    hosts:
      - h0:1
