name: app-base.beam-form
cluster: ${CLUSTER}
parameters:
  initial_status: RUNNING
  message_router: message-router

jobs:
  wait-queue:
    base_image: hub.cstcloud.cn/scalebox/agent

  beam-make:
    base_image: ${MWA_VCSTOOLS}
    command: ${ROCM_COMMAND}
    arguments:
      slot_options: reserved_on_exit
      code_path: ${CODE_BASE}/beam-make/code
    parameters:
      key_group_regex: ^([0-9]+)$
      start_message:
    environments:
      - LOCAL_INPUT_ROOT=
      - LOCAL_OUTPUT_ROOT=
      - KEEP_TARGET_FILE=yes
      - POINTING_RANGE=p00001_00048
    hosts:
      - n-02:1
      # - n-0[12]:${NUM_SLOTS}
    sink_jobs:
      - down-sample

  down-sample:
    base_image: ${DOWN_SAMPLE}
    command: ${DOWN_SAMPLE_COMMAND}
    arguments:
      # 20-min
      max_sleep_count: 200
      slot_options: reserved_on_exit
      code_path: ${CODE_BASE}/down-sample/code
    parameters:
      key_group_regex: ^([0-9]+)$
    environments:
      - LOCAL_INPUT_ROOT=
      - LOCAL_OUTPUT_ROOT=
      - KEEP_SOURCE_FILE=no
      - KEEP_TARGET_FILE=no
      - ENABLE_LOCAL_COMPUTE=yes
    hosts:
      - n-02:1
      # - n-0[12]:1

  fits-merge:
    label: 24通道fits合并
    base_image: app-mwa/mwa-vcstools:rocm-4.0.1
    arguments:
    # 1 hour
      max_sleep_count: 720
      slot_options: reserved_on_exit
      code_path: /raid0/root/app-mwa/pipelines/beam-form/modules/fits-merge/code
    parameters:
      key_group_regex: ^(.+)$
    hosts:
      - h0:1

  message-router:
    base_image: app-mwa/message-router-app-base
    parameters:
      key_group_regex: ^([0-9]+)$
      # start_message: 1257010784/p00001_00120
      # start_message: 1257010784/p00001_00120/t1257012766_1257012965
      start_message: 1257617424/p00001_00048/t1257617426_1257617505
    hosts:
      - h0:1

