name: main.app-mwa
label: comput
cluster: dcu
parameters:
  initial_status: RUNNING

jobs:
  copy-untar:
    base_image: hub.cstcloud.cn/scalebox/agent

  beam-maker:
    base_image: app-mwa/beam-maker

  fits-dist:
    base_image: hub.cstcloud.cn/scalebox/rsync-copy

  fits-merger:
    base_image: app-mwa/fits-merger

  message-router-main:
    base_image: app-mwa/message-router-go
