name: app.beam-form
cluster: ${CLUSTER}
parameters:
  initial_status: RUNNING
  message_router: message-router-beam-form

jobs:
  wait-queue:
    base_image: hub.cstcloud.cn/scalebox/agent

  pull-unpack:
    base_image: ${FILE_COPY}
    arguments:
      code_path: ${CODE_BASE}/pull-unpack/code
      slot_options: tmpfs_workdir
      dir_free_gb: /tmp/scalebox/mydata/mwa/dat~17
      dir_limit_gb: /tmp/scalebox/mydata/mwa/dat~120
    parameters:
      task_dist_mode: HOST-BOUND
      pod_id: pod_beam_form
    environments:
      - SOURCE_URL=${SOURCE_URL}
      - SOURCE_JUMP_SERVERS=${SOURCE_JUMP_SERVERS}
      - TARGET_SUBDIR=${TARGET_SUBDIR}
      - TARGET_URL=${TARGET_URL}
      - BW_LIMIT=100m
    hosts:
      - ${NODES}    

  beam-make:
    base_image: ${MWA_VCSTOOLS}
    command: ${ROCM_COMMAND}
    arguments:
      code_path: ${CODE_BASE}/beam-make/code
      task_timeout_seconds: 3600
      # task_progress_diff: 6
      # 避免工作目录放在 /tmp下，被定期删除
      slot_options: tmpfs_workdir
      dir_free_gb: ${BEAM_MAKE_DIR_FREE_GB}
    parameters:
      task_dist_mode: HOST-BOUND
      pod_id: pod_beam_form
      key_group_regex: ^([0-9]+)
      retry_rules: "['*']"
      max_tasks_per_minute: 3
      message_router_index: 1
      task_cache_expired_minutes: 65
    environments:
      - INPUT_ROOT=${LOCAL_TMP_ROOT}
      - OUTPUT_ROOT=${LOCAL_SHM_ROOT}
      - KEEP_TARGET_FILE=yes
      - POINTING_RANGE=${POINTING_RANGE}
      - ZSTD_TARGET_FILE=no
    hosts:
      - ${NODES}:4

  down-sample:
    base_image: ${DOWN_SAMPLE}
    command: ${DOWN_SAMPLE_COMMAND}
    arguments:
      code_path: ${CODE_BASE}/down-sample/code
      dir_free_gb: ${DOWN_SAMPLE_DIR_FREE_GB}
      # 20-min
      max_sleep_count: 200
      # 避免工作目录放在 /tmp下，被定期删除
      slot_options: tmpfs_workdir
    parameters:
      key_group_regex: ^([0-9]+)
      task_dist_mode: HOST-BOUND
      pod_id: pod_beam_form
    environments:
      - INPUT_ROOT=${LOCAL_SHM_ROOT}
      - OUTPUT_ROOT=${LOCAL_SHM_ROOT}
      - KEEP_SOURCE_FILE=no
      - KEEP_TARGET_FILE=
      - ENABLE_LOCAL_COMPUTE=yes
    hosts:
      - ${NODES}

  fits-redist:
    base_image: ${FILE_COPY}
    arguments:
      code_path: ${CODE_BASE}/fits-redist/code
      # 20-min
      max_sleep_count: 200
      # 避免工作目录放在 /tmp下，被定期删除
      slot_options: tmpfs_workdir
    parameters:
      key_group_regex: ^([0-9]+)
      task_dist_mode: HOST-BOUND
      pod_id: pod_beam_form
      retry_rules: "['*']"
    environments:
      # 1chx
      - INPUT_ROOT=${LOCAL_SHM_ROOT}
      # 1chy
      - OUTPUT_ROOT=${LOCAL_SHM_ROOT}
      # 1chz
      - TARGET_ROOT=${LOCAL_SHM_ROOT}
      - TARGET_USER=${TARGET_USER}
      - TARGET_PORT=${TARGET_PORT}
      - KEEP_SOURCE_FILE=no
    hosts:
      - ${NODES}

  fits-merge:
    label: 24通道fits合并
    base_image: ${MWA_VCSTOOLS}
    arguments:
      code_path: ${CODE_BASE}/fits-merge/code
    # 1 hour
      max_sleep_count: 720
      # 避免工作目录放在 /tmp下，被定期删除
      slot_options: tmpfs_workdir
    parameters:
      key_group_regex: ^([0-9]+)
      task_dist_mode: HOST-BOUND
    environments:
      - INPUT_ROOT=${LOCAL_SHM_ROOT}
      - OUTPUT_ROOT=
      - KEEP_SOURCE_FILE=no
      # "500k"/"1m"/...
      - BW_LIMIT=
    hosts:
      - ${NODES}

  message-router-beam-form:
    base_image: app-mwa/message-router-beam-form-app
    parameters:
      key_group_regex: ^([0-9]+)$
      start_message: ${START_MESSAGE}
      task_dist_mode: SLOT-BOUND
      bulk_message_size: 10
    environments:
      - TIME_STEP=${TIME_STEP}
      - NODES=${NODES}
      # 用于删除 dat 文件
      - SSH_USER=${TARGET_USER}
      - SSH_PORT=${TARGET_PORT}
      - REDISCLI_HOST=
    hosts:
      - h0:2
