name: app.beam-form
cluster: ${CLUSTER}
parameters:
  initial_status: RUNNING
  message_router: mr-beam-form
  slot_group: '{"pull-unpack":1,"beam-make":4,"down-sample":1,"fits-redist":1}'

jobs:
  tar-load:
    base_image: hub.cstcloud.cn/scalebox/file-copy
    slots: 
      - h0:3

  cube-vtask:
    base_image: hub.cstcloud.cn/scalebox/agent
    arguments:
      slot_options: slot_on_head
    parameters:
      # global_vtask_size: 2

  pull-unpack:
    base_image: ${FILE_COPY}
    command: ${COMMAND_TEMPLATE}
    arguments:
      code_path: ${CODE_BASE}/pull-unpack/code
      slot_options: tmpfs_workdir
      dir_free_gb: /tmp/scalebox/mydata/mwa/dat:15
      dir_limit_gb: /tmp/scalebox/mydata/mwa/dat:${PULL_UNPACK_LIMIT_GB}
    parameters:
      task_dist_mode: HOST-BOUND
      pod_id: by_channel
      message_router_index: 2
      key_group_regex: ^([0-9]+)
    environments:
      - SOURCE_URL=${SOURCE_TAR_ROOT}
      - SOURCE_JUMP_SERVERS=${SOURCE_JUMP_SERVERS}
      - TARGET_SUBDIR=${TARGET_SUBDIR}
      - TARGET_URL=${TARGET_URL}
      - BW_LIMIT=${BW_LIMIT}
      - KEEP_SOURCE_FILE=yes
      - TMPDIR_GROUP=39
    slots:
      - ${NODES}    

  beam-make:
    base_image: ${MWA_VCSTOOLS}
    command: ${ROCM_COMMAND}
    arguments:
      code_path: ${CODE_BASE}/beam-make/code
      task_max_seconds: 3600
      sleep_interval_seconds: 60
      task_min_seconds: 30
      # 避免工作目录放在 /tmp下，被定期删除
      slot_options: tmpfs_workdir
      dir_free_gb: /dev/shm/scalebox/mydata:${BEAM_MAKE_FREE_GB}
    parameters:
      task_dist_mode: HOST-BOUND
      pod_id: by_channel
      task_progress_group_diff: 6
      key_group_regex: ^([0-9]+)
      retry_rules: "['*:2','134:9','139:9']"
      slot_timeout_minutes: 30
      slot_recoverable: yes
      # deprecated
      # max_tasks_per_minute: 3
      message_router_index: 1
      task_cache_expired_minutes: 65
    environments:
      - INPUT_ROOT=${LOCAL_TMP_ROOT}
      - OUTPUT_ROOT=${LOCAL_SHM_ROOT}
      - KEEP_TARGET_FILE=yes
      - POINTING_RANGE=${POINTING_RANGE}
      - ZSTD_TARGET_FILE=no
      # 精搜的指向文件名
      - POINTING_FILE=${POINTING_FILE}
      - TMPDIR_GROUP=39
    slots:
      - ${NODES}:${NUM_BEAM_MAKE}
      - ${GROUP_NODES}:2:d00

  down-sample:
    base_image: ${DOWN_SAMPLE}
    command: ${COMMAND_TEMPLATE}
    arguments:
      code_path: ${CODE_BASE}/down-sample/code
      # dir_free_gb: /dev/shm/scalebox/mydata/mwa:${DOWN_SAMPLE_FREE_GB}
      # 20-min
      max_sleep_count: 200
      # 避免工作目录放在 /tmp下，被定期删除
      slot_options: tmpfs_workdir
    parameters:
      key_group_regex: ^([0-9]+)
      task_dist_mode: HOST-BOUND
      pod_id: by_channel
      retry_rules: "['*:2']"
    environments:
      - INPUT_ROOT=${LOCAL_SHM_ROOT}
      - OUTPUT_ROOT=${LOCAL_SHM_ROOT}
      - KEEP_SOURCE_FILE=no
      - KEEP_TARGET_FILE=
      - ENABLE_LOCAL_COMPUTE=yes
      - TMPDIR_GROUP=39
    slots:
      - ${NODES}
      - ${GROUP_NODES}

  fits-redist:
    base_image: ${FILE_COPY}
    command: ${COMMAND_TEMPLATE}
    arguments:
      code_path: ${CODE_BASE}/fits-redist/code
      # 20-min
      max_sleep_count: 200
      # 避免工作目录放在 /tmp下，被定期删除
      slot_options: tmpfs_workdir
    parameters:
      key_group_regex: ^([0-9]+)
      task_dist_mode: HOST-BOUND
      pod_id: by_channel
      retry_rules: "['*:2']"
    environments:
      # 1chx
      - INPUT_ROOT=${LOCAL_SHM_ROOT}
      # 1chy
      - OUTPUT_ROOT=${LOCAL_SHM_ROOT}
      # 1chz
      - TARGET_ROOT=${LOCAL_SHM_ROOT}
      - TARGET_USER=${TARGET_USER}
      - TARGET_PORT=${TARGET_PORT}
      - KEEP_SOURCE_FILE=no
      - TMPDIR_GROUP=39
    slots:
      - ${NODES}
      - ${GROUP_NODES}

  fits-merge:
    label: 24通道fits合并
    command: ${COMMAND_TEMPLATE}
    base_image: ${MWA_VCSTOOLS}
    arguments:
      code_path: ${CODE_BASE}/fits-merge/code
    # 1 hour
      max_sleep_count: 720
      # 避免工作目录放在 /tmp下，被定期删除
      slot_options: tmpfs_workdir
    parameters:
      key_group_regex: ^([0-9]+)
      task_dist_mode: HOST-BOUND
      pod_id: by_pointing
      retry_rules: "['*:2']"
    environments:
      - INPUT_ROOT=${LOCAL_SHM_ROOT}
      - OUTPUT_ROOT=
      - KEEP_SOURCE_FILE=no
      # "500k"/"1m"/...
      - BW_LIMIT=20m
      - TMPDIR_GROUP=39
    slots:
      - ${NODES}
      - ${PRESTO_NODES}

  fits24ch-copy:
    base_image: ${FILE_COPY}
    command: ${COMMAND_TEMPLATE}
    arguments:
      slot_options: tmpfs_workdir
    parameters:
      key_group_regex: ^([0-9]+)
      task_dist_mode: HOST-BOUND
      pod_id: by_pointing
    environments:
      - SOURCE_URL=${LOCAL_SHM_ROOT}
      - TARGET_URL=
      - TARGET_JUMP_SERVERS=${TARGET_JUMP}
      - KEEP_SOURCE_FILE=no
    slots:
      - ${NODES}

  fits24ch-unload:
    base_image: ${FILE_COPY}

  mr-beam-form:
    base_image: app-mwa/message-router-beam-form-app
    parameters:
      key_group_regex: ^([0-9]+)
      start_message: ${START_MESSAGE}
      task_dist_mode: SLOT-BOUND
      bulk_message_size: 2
      slot_options: reserved_on_exit
    environments:
      # 'none' / 'multi-account-relay' / 'single-account-relay'
      - PRELOAD_MODE=${PRELOAD_MODE}
      # 通过命令行指定tar数据的位置（缺省通过*-source.json指定）
      - SOURCE_TAR_ROOT=${SOURCE_TAR_ROOT}
      # 通过命令行指定24ch数据的位置（缺省通过*-target.json指定）
      - TARGET_24CH_ROOT=${TARGET_24CH_ROOT}
      - TIME_STEP=${TIME_STEP}
      - NODES=${NODES}
      # 用于删除 dat 文件
      - SSH_USER=${TARGET_USER}
      - SSH_PORT=${TARGET_PORT}
      - REDISCLI_HOST=
      # 首次加载更高限速，以支持快速加载
      - FIRST_BW_LIMIT=${FIRST_BW_LIMIT}
      #  不同channel数据的计算量不同，交叉分布有助于在各节点上均衡分布计算量，仅针对24个节点以上有效
      - INTERLEAVED_DAT=yes
      # 全并行的波束合成(full_parallel)，隐含着指向优先的排序 POINTING_FIRST=yes
      - RUN_MODE=${RUN_MODE}
      - PRESTO_APP_ID=${PRESTO_APP_ID}
    slots:
      - h0:3
